"""
Component Role: Password Hasher
-------------------------------
This component handles the secure one-way hashing and verification of raw user passwords.

System Relationship:
In a complete authentication flow, the Authenticator or User Registration service relies
on this component to hash passwords before persisting them to the UserRepository, and to
verify incoming plaintext passwords against stored hashes during login. It also assists in
upgrading legacy hashes to stronger algorithmic parameters over time without requiring
user intervention.
"""

from abc import ABC, abstractmethod
import bcrypt

class abstractPasswordHasher(ABC):
    """Abstract interface defining cryptographic password hashing, verification, and upgrade operations."""

    @abstractmethod
    def hash(self, plain_password: str) -> str:
        """
        Produce a secure, salted, one-way hash from a plaintext password string.

        Args:
            plain_password: The raw password provided by the user.

        Returns:
            A formatted string containing the cryptographic hash, salt, and algorithm metadata
            (e.g., algorithm identifier, cost factors, salt, and digest).

        Edge Cases to Consider:
            - Handling empty or null-byte strings.
            - Extremely long password inputs (susceptibility to Denial of Service via algorithmic complexity).
            - Non-ASCII/Unicode normalization (e.g., NFKC normalization before hashing).
            - Enforcing secure random salt generation per hash invocation.
        """
        pass

    @abstractmethod
    def verify(self, plain_password: str, hashed_password: str) -> bool:
        """
        Verify whether a plaintext password matches an existing stored password hash.

        Args:
            plain_password: The raw password provided by the user during authentication.
            hashed_password: The stored hash string previously generated by the hashing mechanism.

        Returns:
            True if the password matches the hash, False otherwise.

        Edge Cases to Consider:
            - Mitigating timing attacks through constant-time comparison.
            - Malformed, truncated, or unrecognized hash format strings.
            - Handling empty plaintext passwords or empty stored hashes safely without throwing unhandled exceptions.
        """
        pass

    @abstractmethod
    def needs_rehash(self, hashed_password: str) -> bool:
        """
        Determine if a stored password hash was created using outdated parameters or an older algorithm.

        Args:
            hashed_password: The stored hash string to inspect.

        Returns:
            True if the hash should be regenerated with updated work factors (e.g., higher iteration count,
            increased memory cost, or modern algorithm), False if it is still compliant.

        Edge Cases to Consider:
            - Malformed hash strings that cannot be parsed for metadata.
            - Hashes produced by legacy schemes (e.g., MD5/SHA-1) that require forced migration.
        """
        pass


class PasswordHasher(abstractPasswordHasher):
    def hash(self, plain_password: str) -> str:
      password_bytes=plain_password.encode("utf-8")
      salt=bcrypt.gensalt()
      hashed_password=bcrypt.hashpw(password_bytes,salt)
      return hashed_password.decode("utf-8")

    def verify(self,plain_password:str,hashed_password:str)->bool:
      try:
        password_bytes=plain_password.encode('utf-8')
        hashed_password_bytes=hashed_password.encode('utf-8')
        return bcrypt.checkpw(password_bytes, hashed_password_bytes)
      except (ValueError, TypeError):
        return False

    def needs_rehash(self, hashed_password: str) -> bool:
      try:
        parts = hashed_password.split("$")
        # Format: ['', '2b', '12', '...'] -> parts[2] is the cost factor
        if len(parts) < 4:
            return True
        current_rounds = int(parts[2])
        target_rounds = 12
        return current_rounds < target_rounds
      except (ValueError, IndexError):
        return True


concretePasswordHasher = PasswordHasher